# ------------ [ C ] ------------
---
If:
  PathMatch: [.*\.c, .*\.h]
CompileFlags:
  Compiler: gcc
  Add: [-xc, -std=c11, -Wall, -Wextra, --target=x86_64-w64-windows-gnu]

# Diagnostics:
  # UnusedIncludes: None
  # Suppress: -Wunused
  ...

  # ------------ [ C++ ] ------------
  ---
If:
  PathMatch: [.*\.cpp, .*\.hpp]
CompileFlags:
  Compiler: g++
  Add: [-xc++, -std=c++17, -Wall, -Wextra, --target=x86_64-w64-windows-gnu]

# Diagnostics:
  # UnusedIncludes: None
  # Suppress: -Wunused
  ...
